// Copyright (c) Epic Games Tools
// Licensed under the MIT license (https://opensource.org/license/mit/)

#ifndef OS_GFX_MAC_KEYCODE_H
#define OS_GFX_MAC_KEYCODE_H

// List of nsevent keycodes
// https://forums.macrumors.com/threads/nsevent-keycode-list.780577/
enum {
  OS_MAC_Keycode_A                = 0x00,
  OS_MAC_Keycode_S                = 0x01,
  OS_MAC_Keycode_D                = 0x02,
  OS_MAC_Keycode_F                = 0x03,
  OS_MAC_Keycode_H                = 0x04,
  OS_MAC_Keycode_G                = 0x05,
  OS_MAC_Keycode_Z                = 0x06,
  OS_MAC_Keycode_X                = 0x07,
  OS_MAC_Keycode_C                = 0x08,
  OS_MAC_Keycode_V                = 0x09,
  OS_MAC_Keycode_B                = 0x0B,
  OS_MAC_Keycode_Q                = 0x0C,
  OS_MAC_Keycode_W                = 0x0D,
  OS_MAC_Keycode_E                = 0x0E,
  OS_MAC_Keycode_R                = 0x0F,
  OS_MAC_Keycode_Y                = 0x10,
  OS_MAC_Keycode_T                = 0x11,
  OS_MAC_Keycode_1                = 0x12,
  OS_MAC_Keycode_2                = 0x13,
  OS_MAC_Keycode_3                = 0x14,
  OS_MAC_Keycode_4                = 0x15,
  OS_MAC_Keycode_6                = 0x16,
  OS_MAC_Keycode_5                = 0x17,
  OS_MAC_Keycode_Equal            = 0x18,
  OS_MAC_Keycode_9                = 0x19,
  OS_MAC_Keycode_7                = 0x1A,
  OS_MAC_Keycode_Minus            = 0x1B,
  OS_MAC_Keycode_8                = 0x1C,
  OS_MAC_Keycode_0                = 0x1D,
  OS_MAC_Keycode_RightBracket     = 0x1E,
  OS_MAC_Keycode_O                = 0x1F,
  OS_MAC_Keycode_U                = 0x20,
  OS_MAC_Keycode_LeftBracket      = 0x21,
  OS_MAC_Keycode_I                = 0x22,
  OS_MAC_Keycode_P                = 0x23,
  OS_MAC_Keycode_L                = 0x25,
  OS_MAC_Keycode_J                = 0x26,
  OS_MAC_Keycode_Quote            = 0x27,
  OS_MAC_Keycode_K                = 0x28,
  OS_MAC_Keycode_Semicolon        = 0x29,
  OS_MAC_Keycode_Backslash        = 0x2A,
  OS_MAC_Keycode_Comma            = 0x2B,
  OS_MAC_Keycode_Slash            = 0x2C,
  OS_MAC_Keycode_N                = 0x2D,
  OS_MAC_Keycode_M                = 0x2E,
  OS_MAC_Keycode_Period           = 0x2F,
  OS_MAC_Keycode_Grave            = 0x32,
  OS_MAC_Keycode_KeypadDecimal    = 0x41,
  OS_MAC_Keycode_KeypadMultiply   = 0x43,
  OS_MAC_Keycode_KeypadPlus       = 0x45,
  OS_MAC_Keycode_KeypadClear      = 0x47,
  OS_MAC_Keycode_KeypadDivide     = 0x4B,
  OS_MAC_Keycode_KeypadEnter      = 0x4C,
  OS_MAC_Keycode_KeypadMinus      = 0x4E,
  OS_MAC_Keycode_KeypadEquals     = 0x51,
  OS_MAC_Keycode_Keypad0          = 0x52,
  OS_MAC_Keycode_Keypad1          = 0x53,
  OS_MAC_Keycode_Keypad2          = 0x54,
  OS_MAC_Keycode_Keypad3          = 0x55,
  OS_MAC_Keycode_Keypad4          = 0x56,
  OS_MAC_Keycode_Keypad5          = 0x57,
  OS_MAC_Keycode_Keypad6          = 0x58,
  OS_MAC_Keycode_Keypad7          = 0x59,
  OS_MAC_Keycode_Keypad8          = 0x5B,
  OS_MAC_Keycode_Keypad9          = 0x5C,
  /* keycodes for keys that are independent of keyboard layout*/
  OS_MAC_Keycode_Return           = 0x24,
  OS_MAC_Keycode_Tab              = 0x30,
  OS_MAC_Keycode_Space            = 0x31,
  OS_MAC_Keycode_Delete           = 0x33,
  OS_MAC_Keycode_Escape           = 0x35,
  OS_MAC_Keycode_Command          = 0x37,
  OS_MAC_Keycode_Shift            = 0x38,
  OS_MAC_Keycode_CapsLock         = 0x39,
  OS_MAC_Keycode_Option           = 0x3A,
  OS_MAC_Keycode_Control          = 0x3B,
  OS_MAC_Keycode_RightShift       = 0x3C,
  OS_MAC_Keycode_RightOption      = 0x3D,
  OS_MAC_Keycode_RightControl     = 0x3E,
  OS_MAC_Keycode_Function         = 0x3F,
  OS_MAC_Keycode_F17              = 0x40,
  OS_MAC_Keycode_VolumeUp         = 0x48,
  OS_MAC_Keycode_VolumeDown       = 0x49,
  OS_MAC_Keycode_Mute             = 0x4A,
  OS_MAC_Keycode_F18              = 0x4F,
  OS_MAC_Keycode_F19              = 0x50,
  OS_MAC_Keycode_F20              = 0x5A,
  OS_MAC_Keycode_F5               = 0x60,
  OS_MAC_Keycode_F6               = 0x61,
  OS_MAC_Keycode_F7               = 0x62,
  OS_MAC_Keycode_F3               = 0x63,
  OS_MAC_Keycode_F8               = 0x64,
  OS_MAC_Keycode_F9               = 0x65,
  OS_MAC_Keycode_F11              = 0x67,
  OS_MAC_Keycode_F13              = 0x69,
  OS_MAC_Keycode_F16              = 0x6A,
  OS_MAC_Keycode_F14              = 0x6B,
  OS_MAC_Keycode_F10              = 0x6D,
  OS_MAC_Keycode_F12              = 0x6F,
  OS_MAC_Keycode_F15              = 0x71,
  OS_MAC_Keycode_Help             = 0x72,
  OS_MAC_Keycode_Home             = 0x73,
  OS_MAC_Keycode_PageUp           = 0x74,
  OS_MAC_Keycode_ForwardDelete    = 0x75,
  OS_MAC_Keycode_F4               = 0x76,
  OS_MAC_Keycode_End              = 0x77,
  OS_MAC_Keycode_F2               = 0x78,
  OS_MAC_Keycode_PageDown         = 0x79,
  OS_MAC_Keycode_F1               = 0x7A,
  OS_MAC_Keycode_LeftArrow        = 0x7B,
  OS_MAC_Keycode_RightArrow       = 0x7C,
  OS_MAC_Keycode_DownArrow        = 0x7D,
  OS_MAC_Keycode_UpArrow          = 0x7E,
  OS_MAC_Keycode_COUNT,
};

global const OS_Key os_mac_gfx_keycode_table[OS_MAC_Keycode_COUNT] = {
  // Alphanumeric
  [OS_MAC_Keycode_0]              = OS_Key_0,  
  [OS_MAC_Keycode_1]              = OS_Key_1,
  [OS_MAC_Keycode_2]              = OS_Key_2,
  [OS_MAC_Keycode_3]              = OS_Key_3,
  [OS_MAC_Keycode_4]              = OS_Key_4,
  [OS_MAC_Keycode_5]              = OS_Key_5,
  [OS_MAC_Keycode_6]              = OS_Key_6,
  [OS_MAC_Keycode_7]              = OS_Key_7,
  [OS_MAC_Keycode_8]              = OS_Key_8,
  [OS_MAC_Keycode_9]              = OS_Key_9,
  [OS_MAC_Keycode_A]              = OS_Key_A,
  [OS_MAC_Keycode_B]              = OS_Key_B,
  [OS_MAC_Keycode_C]              = OS_Key_C,
  [OS_MAC_Keycode_D]              = OS_Key_D,
  [OS_MAC_Keycode_E]              = OS_Key_E,
  [OS_MAC_Keycode_F]              = OS_Key_F,
  [OS_MAC_Keycode_G]              = OS_Key_G,
  [OS_MAC_Keycode_H]              = OS_Key_H,
  [OS_MAC_Keycode_I]              = OS_Key_I,
  [OS_MAC_Keycode_J]              = OS_Key_J,
  [OS_MAC_Keycode_K]              = OS_Key_K,
  [OS_MAC_Keycode_L]              = OS_Key_L,
  [OS_MAC_Keycode_M]              = OS_Key_M,
  [OS_MAC_Keycode_N]              = OS_Key_N,
  [OS_MAC_Keycode_O]              = OS_Key_O,
  [OS_MAC_Keycode_P]              = OS_Key_P,
  [OS_MAC_Keycode_Q]              = OS_Key_Q,
  [OS_MAC_Keycode_R]              = OS_Key_R,
  [OS_MAC_Keycode_S]              = OS_Key_S,
  [OS_MAC_Keycode_T]              = OS_Key_T,
  [OS_MAC_Keycode_U]              = OS_Key_U,
  [OS_MAC_Keycode_V]              = OS_Key_V,
  [OS_MAC_Keycode_W]              = OS_Key_W,
  [OS_MAC_Keycode_X]              = OS_Key_X,
  [OS_MAC_Keycode_Y]              = OS_Key_Y,
  [OS_MAC_Keycode_Z]              = OS_Key_Z,

  // Other characters
  [OS_MAC_Keycode_Grave]          = OS_Key_Tick,
  [OS_MAC_Keycode_LeftBracket]    = OS_Key_LeftBracket,
  [OS_MAC_Keycode_Minus]          = OS_Key_Minus,
  [OS_MAC_Keycode_Period]         = OS_Key_Period,
  [OS_MAC_Keycode_Quote]          = OS_Key_Quote,
  [OS_MAC_Keycode_RightBracket]   = OS_Key_RightBracket,
  [OS_MAC_Keycode_Slash]          = OS_Key_Slash,
  [OS_MAC_Keycode_Space]          = OS_Key_Space,
  [OS_MAC_Keycode_Semicolon]      = OS_Key_Semicolon,
  [OS_MAC_Keycode_Comma]          = OS_Key_Comma,
  [OS_MAC_Keycode_Backslash]      = OS_Key_BackSlash,
  [OS_MAC_Keycode_Equal]          = OS_Key_Equal,

  // Arrows
  [OS_MAC_Keycode_LeftArrow]      = OS_Key_Left,
  [OS_MAC_Keycode_RightArrow]     = OS_Key_Right,
  [OS_MAC_Keycode_DownArrow]      = OS_Key_Down,
  [OS_MAC_Keycode_UpArrow]        = OS_Key_Up,
  
  // Function row
  [OS_MAC_Keycode_F1]             = OS_Key_F1,
  [OS_MAC_Keycode_F2]             = OS_Key_F2,
  [OS_MAC_Keycode_F3]             = OS_Key_F3,
  [OS_MAC_Keycode_F4]             = OS_Key_F4,
  [OS_MAC_Keycode_F5]             = OS_Key_F5,
  [OS_MAC_Keycode_F6]             = OS_Key_F6,
  [OS_MAC_Keycode_F7]             = OS_Key_F7,
  [OS_MAC_Keycode_F8]             = OS_Key_F8,
  [OS_MAC_Keycode_F9]             = OS_Key_F9,
  [OS_MAC_Keycode_F10]            = OS_Key_F10,
  [OS_MAC_Keycode_F11]            = OS_Key_F11,
  [OS_MAC_Keycode_F12]            = OS_Key_F12,
  [OS_MAC_Keycode_F13]            = OS_Key_F13,
  [OS_MAC_Keycode_F14]            = OS_Key_F14,
  [OS_MAC_Keycode_F15]            = OS_Key_F15,
  [OS_MAC_Keycode_F16]            = OS_Key_F16,
  [OS_MAC_Keycode_F17]            = OS_Key_F17,
  [OS_MAC_Keycode_F18]            = OS_Key_F18,
  [OS_MAC_Keycode_F19]            = OS_Key_F19,
  [OS_MAC_Keycode_F20]            = OS_Key_F20,

  // Keypad
  [OS_MAC_Keycode_Keypad1]        = OS_Key_Num1,
  [OS_MAC_Keycode_Keypad0]        = OS_Key_Num0,
  [OS_MAC_Keycode_Keypad2]        = OS_Key_Num2,
  [OS_MAC_Keycode_Keypad3]        = OS_Key_Num3,
  [OS_MAC_Keycode_Keypad4]        = OS_Key_Num4,
  [OS_MAC_Keycode_Keypad5]        = OS_Key_Num5,
  [OS_MAC_Keycode_Keypad6]        = OS_Key_Num6,
  [OS_MAC_Keycode_Keypad7]        = OS_Key_Num7,
  [OS_MAC_Keycode_Keypad8]        = OS_Key_Num8,
  [OS_MAC_Keycode_Keypad9]        = OS_Key_Num9,
  [OS_MAC_Keycode_KeypadClear]    = OS_Key_Backspace,
  [OS_MAC_Keycode_KeypadDecimal]  = OS_Key_NumPeriod,
  [OS_MAC_Keycode_KeypadDivide]   = OS_Key_NumSlash,
  [OS_MAC_Keycode_KeypadEnter]    = OS_Key_Return,
  [OS_MAC_Keycode_KeypadEquals]   = OS_Key_Equal,
  [OS_MAC_Keycode_KeypadMinus]    = OS_Key_NumMinus,
  [OS_MAC_Keycode_KeypadMultiply] = OS_Key_NumStar,
  [OS_MAC_Keycode_KeypadPlus]     = OS_Key_NumPlus,
  
  // Control keys
  [OS_MAC_Keycode_Escape]         = OS_Key_Esc,
  [OS_MAC_Keycode_Tab]            = OS_Key_Tab,
  [OS_MAC_Keycode_PageDown]       = OS_Key_PageDown,
  [OS_MAC_Keycode_PageUp]         = OS_Key_PageUp,
  [OS_MAC_Keycode_Home]           = OS_Key_Home,
  [OS_MAC_Keycode_End]            = OS_Key_End,
  [OS_MAC_Keycode_Delete]         = OS_Key_Backspace, // the backspace key is named "delete" on macs
  [OS_MAC_Keycode_ForwardDelete]  = OS_Key_Delete,
  [OS_MAC_Keycode_Return]         = OS_Key_Return,
  
  // Modifier keys
  [OS_MAC_Keycode_Shift]          = OS_Key_Shift,
  [OS_MAC_Keycode_RightShift]     = OS_Key_Shift,
  [OS_MAC_Keycode_Control]        = OS_Key_Ctrl,
  [OS_MAC_Keycode_RightControl]   = OS_Key_Ctrl,
  [OS_MAC_Keycode_Option]         = OS_Key_Alt,
  [OS_MAC_Keycode_RightOption]    = OS_Key_Alt,
  [OS_MAC_Keycode_CapsLock]       = OS_Key_CapsLock,
  
  // Unhandled keys
  [OS_MAC_Keycode_Command]        = OS_Key_Null, // TODO(yuraiz): figure out how to handle the command key
  [OS_MAC_Keycode_Help]           = OS_Key_Null,
  [OS_MAC_Keycode_Function]       = OS_Key_Null,
  [OS_MAC_Keycode_Mute]           = OS_Key_Null,
  [OS_MAC_Keycode_VolumeDown]     = OS_Key_Null,
  [OS_MAC_Keycode_VolumeUp]       = OS_Key_Null,
};

#endif // OS_GFX_MAC_KEYCODE_H
