name: builds

on:
  push:
    paths-ignore:
      - '**.md'
  pull_request:
    paths-ignore:
      - '**.md'

jobs:
  build-windows-2022:
    runs-on: windows-2025
    strategy:
      fail-fast: false
      matrix:
        target:
          - raddbg
          - radlink
          - radbin
          - mule_main
        compiler:
          - msvc
          - clang
        mode:
          - debug
          - release
    steps:
      - name: checkout
        uses: actions/checkout@v6
      - name: build (vs 2022)
        shell: cmd
        run: |
          call "C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Auxiliary\Build\vcvarsall.bat" x64
          call build meta "${{ matrix.target }}" "${{ matrix.compiler }}" "${{ matrix.mode }}" || exit /b 1

  run-torture:
    runs-on: windows-2025
    strategy:
      fail-fast: false
      matrix:
        compiler:
          - msvc
          - clang
        mode:
          - debug
          - release
        exclude:
          - { compiler: clang, mode: release } # clang runs OOM in release with ASAN
    steps:
      - name: checkout
        uses: actions/checkout@v6
      - name: run-torture
        shell: cmd
        run: |
          call "C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Auxiliary\Build\vcvarsall.bat" x64
          call build asan meta torture radlink radbin "${{matrix.mode}}" "${{matrix.compiler}}" || exit /b 1
          cd build
          torture || exit /b 1

